name: Check PRs for GitHub Issues

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom bot
        id: custom_bot
        uses: your-username/custom-github-bot@v1
        with:
          BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR if no issue reference
        if: steps.custom_bot.outputs.has_issue_reference == 'false'
        run: |
          COMMENT="This pull request does not reference a GitHub issue. Please link to an issue in the PR description."
          echo "${COMMENT}" | gh pr comment ${{ github.event.pull_request.number }} --body -
