name: Inspect PR for GitHub Issue Reference

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  inspect_pr_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run inspection script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
      run: python inspect_pr.py